# Generated by Django 5.0 on 2023-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_set_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
