# Generated by Django 5.0 on 2023-12-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_google_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_password',
        ),
    ]
